name: 'Check for artifacts'
description: 'Test whether a set of artifacts exist'
# https://docs.github.com/en/actions/sharing-automations/creating-actions/metadata-syntax-for-github-actions
inputs:
  filter-file:
    description: Path to the file defining the job filters
    required: true
  workflow-file:
    description: Path to the workflow file
    required: true
  storage-account:
    description: Storage account name
    required: true
  container:
    description: Container name
    required: true
  github-token:
    description: GitHub token for authentication
    required: true
  base-ref:
    description: Base reference for the changes
    required: true
  hash-calculation-type:
    description: The approach to use for calculating file content hashes
outputs:
  jobs:
    description: JSON object keyed on job name with values including whether the job's artifact exists and its artifact key
runs:
  using: 'node20'
  main: 'dist/index.js'
