name: basic

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  workflow_dispatch:

  merge_group:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        # if the checkout script/tool is baked into the base runner image, this step can be skipped as it uses the API to get changes
        # NOTE - that _may_ not be true for the merge group event, need to investigate
        with:
          fetch-depth: 0 # fetch all history for all branches and tags

      - name: run path filter
        id: filter
        run: python ./scripts/process_path_filter.py
        env:
          FILTER_FILE: ./scripts/filter-example.yaml
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Show filter results
        run: |
          printenv | sort
        env:
          FILTER_COMMON: ${{ steps.filter.outputs.common }}
          FILTER_COMMON_SRC: ${{ steps.filter.outputs.common_src }}
          FILTER_COMMON_TEST: ${{ steps.filter.outputs.common_test }}
          FILTER_SRC: ${{ steps.filter.outputs.src }}
          FILTER_TEST: ${{ steps.filter.outputs.test }}


