name: basic-2

on:
  push:
    branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

  workflow_dispatch:

  merge_group:

jobs:
  build:
    runs-on: [self-hosted, ManagedDevOps.Pool=tt-pool2]

    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          printenv | sort
